"""updated tables

Revision ID: 78001089d804
Revises: feda8831ae7f
Create Date: 2025-09-07 15:41:07.952804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78001089d804"
down_revision: Union[str, Sequence[str], None] = "feda8831ae7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orderitems", sa.Column("amount_without_tax", sa.Float(), nullable=False)
    )
    op.add_column("orderitems", sa.Column("tax_amount", sa.Float(), nullable=False))
    op.add_column("orders", sa.Column("net_tax_amount", sa.Float(), nullable=False))
    op.drop_column("orders", "tax_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "tax_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "net_tax_amount")
    op.drop_column("orderitems", "tax_amount")
    op.drop_column("orderitems", "amount_without_tax")
    # ### end Alembic commands ###
