"""updated tables

Revision ID: cf5d2dac657a
Revises: 3e2bc8576adf
Create Date: 2025-09-07 10:33:12.169903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf5d2dac657a"
down_revision: Union[str, Sequence[str], None] = "3e2bc8576adf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("net_amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "net_amount")
    # ### end Alembic commands ###
