"""updated tables

Revision ID: feda8831ae7f
Revises: cf5d2dac657a
Create Date: 2025-09-07 10:38:15.206552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feda8831ae7f"
down_revision: Union[str, Sequence[str], None] = "cf5d2dac657a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("net_amount_without_tax", sa.Float(), nullable=False)
    )
    op.add_column("orders", sa.Column("tax_amount", sa.Float(), nullable=False))
    op.drop_column("orders", "net_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "net_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "tax_amount")
    op.drop_column("orders", "net_amount_without_tax")
    # ### end Alembic commands ###
